name: bio_ds_env

channels:

  - conda-forge
  - bioconda
  - defaults

dependencies:
  
  # Core Package Management

  - python=3.9.21
  - pip=25.0.1
  
  # Bioinformatics Command-line Tools

  - bedtools=2.31.1
  - bcftools=1.21
  - htslib=1.21
  - nextflow=24.10.4
  - samtools=1.21
  - setuptools=75.8.0

  # Python packages
  - pip:
    - PyYAML==6.0.2
    - apache-beam==2.62.0
    - biopython==1.85
    - black==25.1.0
    - datasets==3.2.0
    - fastapi==0.115.8
    - fastparquet==2024.11.0
    - gffutils==0.13
    - gql==3.5.0
    - h5py==3.12.1
    - ipykernel==6.29.5
    - jupyterlab==4.3.5
    - lightgbm==4.5.0
    - matplotlib==3.9.4
    - mlflow==2.20.1
    - numpy==2.0.2
    - openpyxl==3.1.5
    - pandas==2.2.3
    - plotly==6.0.0
    - pyBigWig==0.3.24
    - pyarrow==16.1.0
    - pylint==3.3.4
    - pysam==0.23.0
    - pyspark==3.5.4
    - pytest==8.3.4
    - requests==2.32.3
    - s3fs==2023.6.0
    - scanpy==1.10.3
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - squidpy==1.6.0
    - statsmodels==0.14.4
    - streamlit==1.42.0
    - tensorflow-cpu==2.18.0
    - torch==2.6.0
    - tqdm==4.67.1
    - transformers==4.48.3
    - uvicorn==0.34.0
    - wandb==0.19.6
    - xgboost==2.1.4
