[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_package"
version = "0.0.0"
readme = "README.md"

[tool.setuptools]
packages = ["my_package"]
package-dir = {"" = "src"}